@startuml
autonumber
participant Bob order 10 #aqua
participant Alice [
=Title
----
""SubTitle""
]
actor Bob #red
' The only difference between actor
'and participant is the drawing
participant Alice
participant "I have a really\nlong name" as L #99FF99
/' You can also declare:
participant L as "I have a really\nlong name" #99FF99
'/
Alice->x Bob: Authentication Request
Bob<->>o Alice: Authentication Response
autonumber 20
Bob->L: Log transaction
Alice <<-[#red]>Alice: Self\nMultiline
Alice->Bob: Authentication Request
@enduml